/*
 * Swagger Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client;

/**
 * Api-related assert logic.
 */
public class ApiAsserts {
    /**
     * Checks the assertion the supplied parameter is not null.
     *
     * @param apiMethod api method this parameter is being used in
     * @param parameter parameter name
     * @param value     value supplied to api method
     * @throws ApiException when assertion fails
     */
    public static void notNull(String apiMethod, String parameter, Object value) throws ApiException {
        if (value == null) {
            throw new ApiException(String.format("Missing the required parameter '%s' when calling %s", parameter, apiMethod));
        }
    }
}
