/*
 * Swagger Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client;

/**
 * Factory for ProgressListener(s), typically used in generated code.
 */
public class ProgressListenerFactory {
    /**
     * Generates listener instance calling back the provided callback.
     *
     * @param callback callback to call on response body update notification
     * @return new instance if callback is not null
     */
    public static <T> ProgressResponseBody.ProgressListener newInstance(final ApiCallback<T> callback) {
        if (callback != null) {
            return new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };
        } else {
            return null;
        }
    }
}
