/*
 * Swagger Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client;

import com.squareup.okhttp.Request;
import com.squareup.okhttp.RequestBody;

/**
 * Decorates outgoing requests.
 */
public interface ApiClientRequestDecorator {
    /**
     * Decorates outgoing request.
     *
     * @param requestBuilder request builder to use for decoration
     * @param requestBody    request body
     */
    void decorateRequest(Request.Builder requestBuilder, RequestBody requestBody);
}
