/*
 * Swagger Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client;

import com.squareup.okhttp.Interceptor;
import com.squareup.okhttp.Response;

import java.io.IOException;

/**
 * Factory for network Interceptor(s).
 */
public class InterceptorFactory {
    /**
     * Generates interceptor instance for progress listener.
     *
     * @param progressListener progress listener
     * @return new instance if progress listener is not null
     */
    public static Interceptor newInstance(final ProgressResponseBody.ProgressListener progressListener) {
        if (progressListener != null) {
            return new Interceptor() {
                @Override
                public Response intercept(Chain chain) throws IOException {
                    Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                            .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                            .build();
                }
            };
        } else {
            return null;
        }
    }
}
