/*
 * Swagger Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

import io.swagger.client.Pair;

import java.util.Date;
import java.util.Map;
import java.util.List;


public class OAuth implements Authentication {
    private OAuthBearerProvider bearerProvider;
    private String accessToken;
    private Date expiration;

    public OAuthBearerProvider getBearerProvider() {
        return bearerProvider;
    }

    public void setBearerProvider(OAuthBearerProvider bearerProvider) {
        this.bearerProvider = bearerProvider;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public Date getExpiration() {
        return expiration;
    }

    public void setExpiration(Date expiration) {
        this.expiration = expiration;
    }

    @Override
    public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams) {
        if (accessToken != null && expiration != null) {
            if (System.currentTimeMillis() > expiration.getTime()) {
                accessToken = null;
                expiration = null;
            }
        }
        if (accessToken == null && bearerProvider != null) {
            bearerProvider.provideAccessToken(this);
        }
        if (accessToken != null) {
            headerParams.put("Authorization", "Bearer " + accessToken);
        }
    }
}
